#!/usr/bin/env python3

QUEUE_NAME = "worker_queue"
HOST_NAME = "rabbitmq"
HOST_PORT = 5672
REQUEST_SEPARATOR = '-'

TEMP_FOLDER = "temp/"
IMAGE_FOLDER = "temp/image/"
VIDEO_FOLDER = "temp/video/"
OUTPUT_FOLDER = "temp/output/"

API_CONTAINER_NAME = "django"
IMAGE_ADDRESS = f"http://{API_CONTAINER_NAME}:8000/images/"
VIDEO_ADDRESS = f"http://{API_CONTAINER_NAME}:8000/videos/"

IMAGE_PROPERTY_DATA = "data"

VIDEO_PROPERTY_NAME = "name"
VIDEO_PROPERTY_DATA = "data"

IMAGE_EXTENSION = ".png"
VIDEO_EXTENSION = ".mp4"

VIDEO_WIDTH = 640
VIDEO_HEIGHT = 480

VIDEO_IMAGE_DURATION = 0.5
