# Generated by Django 3.1.4 on 2020-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.ImageField(default='empty', upload_to='image_uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.FileField(default='empty', upload_to='video_uploads/'),
            preserve_default=False,
        ),
    ]
