# Generated by Django 3.1.4 on 2020-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201229_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
