name: Complete Docker Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      frontend-directory: AwesomeTimelapseFrontend
      rest-directory: AwesomeTimelapseREST
      backend-directory: AwesomeTimelapseBackend
      version: 0.1

    steps:
    - uses: actions/checkout@v2
    - name: Build the Frontend-Dockerfile
      run: docker build .
      working-directory: ${{env.frontend-directory}}
    - name: Build the REST-Dockerfile
      run: docker build .
      working-directory: ${{env.rest-directory}}
    - name: Build the Backend-Dockerfile
      run: docker build .
      working-directory: ${{env.backend-directory}}
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PWD }}
    - name: Tag the Docker Images
      run: docker tag ase-awesometimelapse_api ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_api:${{env.version}} && docker tag ase-awesometimelapse_worker ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_worker:${{env.version}} && docker tag ase-awesometimelapse_frontend ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_frontend:${{env.version}}
    - name: Push the Docker Images
      run: docker push ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_api:${{env.version}} && docker push ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_worker:${{env.version}} && docker push ${{ secrets.DOCKER_USER}}/ase-awesometimelapse_frontend:${{env.version}}
